### ISSUE TITLE
cropping policy

### ISSUE THREAD

**Issue by Play2Boy** [vinayprabhu/Saliency_Image_Cropping#1]
when I get saliency map, how to crop an image ?

**Comment by vinayprabhu** [comment]
Thanks for your question!
In order to maintain consistency in comparisons, we used the same [`plot_crop_area`](https://github.com/twitter-research/image-crop-analysis/blob/d66ad3bb3881fdbd12a27e04c3e57cc8fd772dd1/src/crop_api.py#L192) function from [here](https://github.com/twitter-research/image-crop-analysis/blob/main/src/crop_api.py).
```
    def plot_crop_area(
        self,
        img,
        salient_x,
        salient_y,
        aspectRatio,
        ax=None,
        original_crop=None,
        checkSymmetry=True,
    )
```
Basically, the ELI-5 idea is: Img --> saliency-map --> max-saliency point --> draw a rect around it that adheres to the aspect ratio.

We are in the process of adding in all the notebooks used to generate the results in the coming week(s). Stay tuned!
